import "./globals.css";


export const metadata = {
  title: "Property List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-dark-blue font-display">{children}</body>
    </html>
  );
}
